# Numpy Tasks

## Task_1

#### Question 1. Create a numpy array with 6X5 2D array from 10 upwards

In [6]:
import numpy as np

array = np.arange(10,40).reshape(6,5)
print(array)

[[10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]
 [30 31 32 33 34]
 [35 36 37 38 39]]


#### Question 2. From question 1, reshape the numpy array to any shape of your choice and return the max value from each column.

In [10]:
array2 = array.reshape(10,3)
print(array2)
print("The max value from each column is ",array2.max(axis=0))

[[10 11 12]
 [13 14 15]
 [16 17 18]
 [19 20 21]
 [22 23 24]
 [25 26 27]
 [28 29 30]
 [31 32 33]
 [34 35 36]
 [37 38 39]]
The max value from each column is  [37 38 39]


#### Question 3. Create a numpy array A with np.ones with a shape of (3,4). Create another array using the np.arange with a shape of (3,4). 

In [12]:
array3 = np.ones((3,4))
array4 = np.arange(1,13).reshape(3,4)
print(array3)
print(array4)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


#### Question 4. Perform arithmetic operations (+,-,*,/) on the two arrays from question 3.

In [14]:
addition = array3 + array4
subtraction = array4 - array3
multiplication = array3 * array4
division = array4 / array3

print("Addition(+) : ", addition)
print("Subtraction(-) : ", subtraction)
print("Multiplication(*) : ", multiplication)
print("Division(/) : ", division)

Addition(+) :  [[ 2.  3.  4.  5.]
 [ 6.  7.  8.  9.]
 [10. 11. 12. 13.]]
Subtraction(-) :  [[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]
Multiplication(*) :  [[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]]
Division(/) :  [[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]]


#### Question 5. From question 4, transpose the results of each arithmetic operation.

In [15]:
print(np.transpose(addition))
print(np.transpose(subtraction))
print(np.transpose(multiplication))
print(np.transpose(division))

[[ 2.  6. 10.]
 [ 3.  7. 11.]
 [ 4.  8. 12.]
 [ 5.  9. 13.]]
[[ 0.  4.  8.]
 [ 1.  5.  9.]
 [ 2.  6. 10.]
 [ 3.  7. 11.]]
[[ 1.  5.  9.]
 [ 2.  6. 10.]
 [ 3.  7. 11.]
 [ 4.  8. 12.]]
[[ 1.  5.  9.]
 [ 2.  6. 10.]
 [ 3.  7. 11.]
 [ 4.  8. 12.]]
